### ISSUE TITLE
0.11.15 build fails on Rust 1.62

### ISSUE THREAD

**Issue by YuhanLiin** [jonhoo/inferno#283]
Building the latest version on Rust 1.62 fails with:
```
error[E0106]: missing lifetime specifier
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/inferno-0.11.15/src/flamegraph/color/mod.rs:83:25
   |
83 |     pub const VARIANTS: &[&'static str] = &[
   |                         ^ expected named lifetime parameter
   |
help: consider using the `'static` lifetime
   |
83 |     pub const VARIANTS: &'static [&'static str] = &[
   |                          +++++++
help: consider introducing a named lifetime parameter
   |
81 ~ impl<'a> Palette {
82 |     /// The valid set of palettes (via `FromStr`).
83 ~     pub const VARIANTS: &'a [&'static str] = &[
   |
```
The build works on v0.11.14.

**Comment by jonhoo** [comment]
Unfortunately you're going to need Rust 1.64.0 now because of the upgrade to clap 4 (https://github.com/jonhoo/inferno/pull/267), as well as another couple of newer features we started making use of.
